/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INT GENERATED ALWAYS AS IDENTITY,
    name TEXT,
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL
);

ALTER TABLE ANIMALS ADD COLUMN SPECIES TEXT;

CREATE TABLE owners ( 
  id SERIAL PRIMARY KEY, 
  full_name TEXT, 
  age INT
);

CREATE TABLE species ( 
  id INT SERIAL PRIMARY KEY, 
  name TEXT
);

ALTER TABLE ANIMALS DROP COLUMN ID;
ALTER TABLE ANIMALS ADD COLUMN ID SERIAL PRIMARY KEY;
ALTER TABLE ANIMALS DROP COLUMN SPECIES;
ALTER TABLE ANIMALS ADD COLUMN SPECIES_ID INT;
ALTER TABLE ANIMALS ADD COLUMN OWNER_ID INT;
ALTER TABLE ANIMALS ADD CONSTRAINT FK_SPECIES_ID FOREIGN KEY(SPECIES_ID) REFERENCES SPECIES(ID);
ALTER TABLE ANIMALS ADD CONSTRAINT FK_OWNER_ID FOREIGN KEY(OWNER_ID) REFERENCES OWNERS(ID);